// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace UNF2020.API.DatabaseModels
{
    public partial class UNF2020Context : DbContext
    {
        public UNF2020Context()
        {
        }

        public UNF2020Context(DbContextOptions<UNF2020Context> options)
            : base(options)
        {
        }

        public virtual DbSet<Placement> Placement { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasAnnotation("Scaffolding:ConnectionString", "Data Source=(local);Initial Catalog=UNF2020;Integrated Security=true");

            modelBuilder.Entity<Placement>(entity =>
            {
                entity.ToTable("Placement", "jobs");

                entity.Property(e => e.Id).ValueGeneratedNever();

                entity.Property(e => e.CompanyCity)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.CompanyName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.CompanyState)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.EndDate).HasColumnType("date");

                entity.Property(e => e.Industry)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PersonFirstName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PersonGender)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PersonLastName)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.PositionTitle)
                    .HasMaxLength(100)
                    .IsUnicode(false);

                entity.Property(e => e.StartDate).HasColumnType("date");

                entity.Property(e => e.StartYearlySalary).HasColumnType("decimal(14, 2)");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}